/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'Inter', 'sans-serif'],
        "label-bold": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"]
      },
      colors: {
        brand: {
          50: '#f0f4ff',
          100: '#e0e9ff',
          200: '#c7d6fe',
          300: '#a5b8fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        accent: {
          400: '#f472b6',
          500: '#ec4899',
          600: '#db2777',
        },
        surface: {
          800: '#1e1b2e',
          900: '#13111f',
          950: '#0a0814',
        },
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e8ea",
        "outline-variant": "#bbcabd",
        "error-container": "#ffdad6",
        "primary-container": "#1dbf73",
        "surface-dim": "#dbd9dc",
        "primary-fixed-dim": "#4de090",
        "on-tertiary-fixed-variant": "#69383d",
        "surface-container-highest": "#e3e2e4",
        "secondary-fixed-dim": "#9cd49d",
        "surface-container": "#efedf0",
        "on-secondary-container": "#3c6f42",
        "primary-fixed": "#6efdaa",
        "surface-gray": "#F4F4F4",
        "surface-tint": "#006d3e",
        "outline": "#6c7b6f",
        "tertiary-fixed": "#ffdadb",
        "primary": "#006d3e",
        "surface": "#faf9fb",
        "tertiary": "#854f54",
        "on-error": "#ffffff",
        "inverse-primary": "#4de090",
        "tertiary-fixed-dim": "#f9b5b9",
        "border-subtle": "#E4E5E7",
        "surface-variant": "#e3e2e4",
        "secondary-container": "#b7f1b8",
        "on-background": "#1a1c1e",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002108",
        "inverse-on-surface": "#f2f0f3",
        "secondary": "#36693c",
        "surface-container-low": "#f4f3f5",
        "on-surface-variant": "#3d4a40",
        "inverse-surface": "#2f3032",
        "on-primary": "#ffffff",
        "trust-green-dark": "#003912",
        "on-tertiary-fixed": "#350e14",
        "on-secondary": "#ffffff",
        "background": "#faf9fb",
        "tertiary-container": "#d7969b",
        "surface-bright": "#faf9fb",
        "on-primary-container": "#004726",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00210f",
        "on-secondary-fixed-variant": "#1d5127",
        "on-primary-fixed-variant": "#00522d",
        "on-tertiary-container": "#5d2e33",
        "secondary-fixed": "#b7f1b8",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c1e",
        "accent-burgundy": "#40171C"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "container-max": "1400px",
        "margin-desktop": "48px",
        "section-gap": "96px",
        "gutter": "24px"
      },
      fontSize: {
        "label-bold": ["14px", {"lineHeight": "16px", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-xl": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'bounce-in': 'bounceIn 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'timer-shrink': 'timerShrink 20s linear forwards',
        'confetti-fall': 'confettiFall 3s ease-in forwards',
        'score-pop': 'scorePop 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideDown: { from: { opacity: 0, transform: 'translateY(-20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        bounceIn: { '0%': { transform: 'scale(0)' }, '60%': { transform: 'scale(1.1)' }, '100%': { transform: 'scale(1)' } },
        pulseGlow: { '0%, 100%': { boxShadow: '0 0 20px rgba(99,102,241,0.4)' }, '50%': { boxShadow: '0 0 40px rgba(99,102,241,0.8)' } },
        timerShrink: { from: { width: '100%' }, to: { width: '0%' } },
        confettiFall: { '0%': { transform: 'translateY(-100px) rotate(0deg)', opacity: 1 }, '100%': { transform: 'translateY(100vh) rotate(720deg)', opacity: 0 } },
        scorePop: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.3)' }, '100%': { transform: 'scale(1)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'mesh-gradient': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
